<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<!-- Inherit defaults from Spring Boot -->
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.0-RC1</version>
		<relativePath/>
	</parent>

	<groupId>com.summer</groupId>
	<artifactId>summer</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>
	<name>summer</name>

    <modules>
        <module>summer-admin</module>
        <module>summer-bootstrap</module>
        <module>summer-framework</module>
        <module>summer-starter</module>
        <module>summer-bom</module>
    </modules>

	<properties>

		<revision>1.0</revision>

		<java.version>17</java.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<jjwt.version>0.10.6</jjwt.version>

		<fastjson.version>1.2.83</fastjson.version>
		<guava.version>31.1-jre</guava.version>

	</properties>

	<dependencies>

	<dependency>
		<groupId>io.jsonwebtoken</groupId>
		<artifactId>jjwt-api</artifactId>
		<version>${jjwt.version}</version>
	</dependency>

	<dependency>
		<groupId>io.jsonwebtoken</groupId>
		<artifactId>jjwt-impl</artifactId>
		<version>${jjwt.version}</version>
		<scope>runtime</scope>
	</dependency>

	<dependency>
		<groupId>io.jsonwebtoken</groupId>
		<artifactId>jjwt-jackson</artifactId>
		<version>${jjwt.version}</version>
		<scope>runtime</scope>
	</dependency>

	<!-- https://mvnrepository.com/artifact/com.alibaba/fastjson -->
	<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>${fastjson.version}</version>
		</dependency>

        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>


		<!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>${guava.version}</version>
		</dependency>

	</dependencies>

    

</project>
